name: nuget

on:
  push:
    tags:
    - '*'

  workflow_dispatch:
    inputs:
      tag: 
        description: 'Tag to release'
        required: true


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --no-restore
    - name: Test
      run: dotnet test ./src --no-build --verbosity normal
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish the package to nuget.org
      run: dotnet nuget push src/Markdig.Renderers.Docx/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

